# 服务端口
server:
  port: 8001

# 服务名
spring:
  application:
    name: service-edu
  # 环境设置：dev(开发环境)、test(测试环境)、prod(生产环境)
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #此处必须加上"characterEncoding=utf8" 否则like模糊查询将会失效
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别  级别优先级: ALL > DEBUG > INFO > WARN > ERROR > FATAL > OFF 默认级别是INFO
logging:
  level:
    root: info

#将日志文件输出到文件中   需要先注释掉上面的两项配置 然后在resources文件夹中创建一个logback-spring.xml文件
